#!/usr/bin/env bash
# crabterm - init, config scan, templates

# -- Template System ----------------------------------------------------------

template_promptfoo_cloud() {
  cat << 'TEMPLATE_EOF'
# Crabterm Configuration - Promptfoo Cloud Template
# Generated by 'crab init --template promptfoo-cloud'

session_name: ALIAS_PLACEHOLDER
workspace_base: WORKSPACE_BASE_PLACEHOLDER
main_repo: MAIN_REPO_PLACEHOLDER

workspaces:
  prefix: cloud-workspace
  branch_pattern: workspace-{N}

layout:
  panes:
    - name: terminal
      command: ""
    - name: server
      command: pnpm dev
    - name: main
      command: claude --dangerously-skip-permissions --chrome

install_command: pnpm install
install_env: PROMPTFOO_NODE_MODULES_CACHED=true

submodules:
  - path: promptfoo
    reset_to: origin/main
    install_command: pnpm install

env_sync:
  port_spacing: 10
  files:
    - path: server/.env
      ports: [API_URL, APP_URL]
      refs:
        API_PORT: API_URL:port
    - path: app/.env
      refs:
        VITE_API_BASE_URL: API_URL
        PORT: APP_URL:port
    - path: admin-app/.env
      refs:
        VITE_API_BASE_URL: API_URL
    - path: promptfoo/.env
      refs:
        PROMPTFOO_REMOTE_GENERATION_URL: API_URL
        PROMPTFOO_UNALIGNED_INFERENCE_ENDPOINT: API_URL
        API_HOST: API_URL

cleanup:
  preserve_files: ".env"
  kill_pattern: "cloud-workspace-{N}.*pnpm|cloud-workspace-{N}.*node"

shared_volume:
  enabled: true
  path: ~/.crabterm/shared
  link_as: .local
TEMPLATE_EOF
}

detect_template() {
  local repo_path="${1:-.}"

  if [ -f "$repo_path/.gitmodules" ] && grep -q "promptfoo" "$repo_path/.gitmodules" 2>/dev/null \
     && [ -f "$repo_path/server/.env.example" ]; then
    echo "promptfoo-cloud"
    return
  fi

  if [[ "$(basename "$repo_path")" == *"promptfoo-cloud"* ]]; then
    echo "promptfoo-cloud"
    return
  fi

  echo ""
}

apply_template() {
  local template_name="$1"
  local main_repo="$2"
  local workspace_base="$3"
  local alias="${4:-crab}"

  local template_content=""
  case "$template_name" in
    "promptfoo-cloud")
      template_content="$(template_promptfoo_cloud)"
      ;;
    *)
      error "Unknown template: $template_name"
      return 1
      ;;
  esac

  mkdir -p "$PROJECTS_DIR"
  echo "$template_content" \
    | sed "s|MAIN_REPO_PLACEHOLDER|$main_repo|g" \
    | sed "s|WORKSPACE_BASE_PLACEHOLDER|$workspace_base|g" \
    | sed "s|ALIAS_PLACEHOLDER|$alias|g" \
    > "$CONFIG_FILE"
}

show_templates() {
  echo -e "${CYAN}Available Templates${NC}"
  echo ""
  echo -e "  ${GREEN}promptfoo-cloud${NC}  Full config for promptfoo-cloud repos"
  echo "                    Includes env_sync, submodules, port_spacing, install_env"
  echo ""
  echo "Usage:"
  echo "  crab init --template promptfoo-cloud"
  echo "  crab init -t promptfoo-cloud"
}

# -- End Template System ------------------------------------------------------

show_init() {
  # Parse arguments
  local template_name=""
  local alias_input=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --template|-t)
        template_name="$2"
        shift 2
        ;;
      --alias|-a)
        alias_input="$2"
        shift 2
        ;;
      --list-templates)
        show_templates
        return
        ;;
      *)
        shift
        ;;
    esac
  done

  echo -e "${CYAN}Crabterm Setup${NC}"
  echo -e "  ${GRAY}Register a project repo. Run 'crab init' again to add more.${NC}"
  echo ""

  # Main repo
  local default_repo=$(pwd)
  echo -e "Path to the repo you want to manage with crab"
  echo -e "  ${GRAY}(crab will create git worktrees from this repo)${NC}"
  read -p "  [$default_repo]: " main_repo
  main_repo=${main_repo:-$default_repo}

  main_repo="${main_repo/#\~/$HOME}"

  if [ ! -d "$main_repo" ]; then
    error "Directory does not exist: $main_repo"
    return 1
  fi

  if [ ! -d "$main_repo/.git" ]; then
    warn "Not a git repository: $main_repo"
    read -p "Continue anyway? [y/N]: " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
      return 1
    fi
  fi

  # Project alias
  if [ -z "$alias_input" ]; then
    local default_alias=$(basename "$main_repo" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g')
    echo ""
    echo -e "Project alias (used in ${GREEN}crab @alias ws 1${NC})"
    read -p "  [$default_alias]: " alias_input
    alias_input=${alias_input:-$default_alias}
  fi

  if ! [[ "$alias_input" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    error "Alias must be alphanumeric (dashes and underscores allowed)"
    return 1
  fi

  if [ -f "$PROJECTS_DIR/${alias_input}.yaml" ]; then
    echo -e "${YELLOW}Project @$alias_input already exists.${NC}"
    read -p "Overwrite? [y/N]: " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
      echo "Cancelled."
      return
    fi
  fi

  CONFIG_FILE="$PROJECTS_DIR/${alias_input}.yaml"
  PROJECT_ALIAS="$alias_input"

  # Workspace base
  local repo_name=$(basename "$main_repo")
  local repo_parent=$(dirname "$main_repo")

  local global_ws_base=""
  if [ -f "$GLOBAL_CONFIG" ]; then
    global_ws_base=$(yq -r '.default_workspace_base // ""' "$GLOBAL_CONFIG" 2>/dev/null)
    [ "$global_ws_base" = "null" ] && global_ws_base=""
  fi


  local default_base
  if [ -n "$global_ws_base" ]; then
    default_base="${global_ws_base/\{alias\}/$alias_input}"
    default_base="${default_base/#\~/$HOME}"
  else
    default_base="$repo_parent/${repo_name}-workspaces"
  fi

  echo ""
  echo -e "Where should workspaces be created?"
  echo -e "  (Each workspace is a git worktree, e.g., ${repo_name}-workspaces/ws-1)"
  read -p "  [$default_base]: " workspace_base
  workspace_base=${workspace_base:-$default_base}

  workspace_base="${workspace_base/#\~/$HOME}"

  # Check for project-level config in repo directory
  local project_config="$main_repo/.crabterm.yaml"
  if [ -f "$project_config" ]; then
    echo ""
    echo -e "${GREEN}Found project config: .crabterm.yaml${NC}"
    read -p "Import settings from it? [Y/n]: " use_project
    if [ "$use_project" != "n" ] && [ "$use_project" != "N" ]; then
      mkdir -p "$PROJECTS_DIR"
      cp "$project_config" "$CONFIG_FILE"

      local main_repo_val=$(yq -r '.main_repo // ""' "$CONFIG_FILE" 2>/dev/null)
      if [ -z "$main_repo_val" ] || [ "$main_repo_val" = "null" ] || [[ "$main_repo_val" == "~/"* ]] || [[ "$main_repo_val" == "./"* ]]; then
        yq -i ".main_repo = \"$main_repo\"" "$CONFIG_FILE"
      fi

      local ws_base_val=$(yq -r '.workspace_base // ""' "$CONFIG_FILE" 2>/dev/null)
      if [ -z "$ws_base_val" ] || [ "$ws_base_val" = "null" ]; then
        yq -i ".workspace_base = \"$workspace_base\"" "$CONFIG_FILE"
      fi

      yq -i ".session_name = \"$alias_input\"" "$CONFIG_FILE"

      _init_set_default_if_first "$alias_input"

      echo ""
      success "Project @$alias_input registered at $CONFIG_FILE"
      echo ""
      echo -e "${CYAN}Next steps:${NC}"
      echo "  1. Review config: crab @$alias_input config"
      echo "  2. Run 'crab @$alias_input config scan' to detect ports"
      echo "  3. Run 'crab @$alias_input ws 1' to create your first workspace"
      return
    fi
    echo ""
  fi

  # Template handling
  if [ -n "$template_name" ]; then
    case "$template_name" in
      "promptfoo-cloud"|"pf")
        template_name="promptfoo-cloud"
        ;;
      *)
        error "Unknown template: $template_name"
        echo "Run 'crab init --list-templates' to see available templates."
        return 1
        ;;
    esac
    echo ""
    echo -e "Applying ${GREEN}$template_name${NC} template..."
    apply_template "$template_name" "$main_repo" "$workspace_base" "$alias_input"
    _init_set_default_if_first "$alias_input"
    echo ""
    success "Project @$alias_input registered at $CONFIG_FILE (template: $template_name)"
    echo ""
    echo -e "${CYAN}Next steps:${NC}"
    echo "  1. Review config: crab @$alias_input config"
    echo "  2. Run 'crab @$alias_input ws 1' to create your first workspace"
    return
  fi

  # Auto-detect template
  local detected
  detected=$(detect_template "$main_repo")
  if [ -n "$detected" ]; then
    echo ""
    echo -e "Detected ${GREEN}$detected${NC} project."
    read -p "Use template? [Y/n]: " use_tpl
    if [ "$use_tpl" != "n" ] && [ "$use_tpl" != "N" ]; then
      echo ""
      echo -e "Applying ${GREEN}$detected${NC} template..."
      apply_template "$detected" "$main_repo" "$workspace_base" "$alias_input"
      _init_set_default_if_first "$alias_input"
      echo ""
      success "Project @$alias_input registered at $CONFIG_FILE (template: $detected)"
      echo ""
      echo -e "${CYAN}Next steps:${NC}"
      echo "  1. Review config: crab @$alias_input config"
      echo "  2. Run 'crab @$alias_input ws 1' to create your first workspace"
      return
    fi
    echo ""
  fi

  # No template - generate minimal config
  mkdir -p "$PROJECTS_DIR"

  cat > "$CONFIG_FILE" << EOF
# Crabterm Configuration
# Generated by 'crab init'
# Project: @$alias_input
# Run 'crab config scan' to auto-detect env files and ports

session_name: $alias_input
workspace_base: $workspace_base
main_repo: $main_repo

workspaces:
  prefix: ws
  branch_pattern: workspace-{N}

layout:
  panes:
    - name: terminal
      command: ""
    - name: server
      command: ""
    - name: main
      command: ""

# Run 'crab config scan' to detect .env files and generate env_sync config
# .env files are copied from the same path in your main repo
# Then edit this file to customize:
#
# env_sync:
#   files:
#     - path: .env               # copied from main_repo/.env
#       ports: [PORT, API_PORT]
#       overrides:               # optional: override env vars in workspaces
#         DEBUG: "true"
#
# layout:
#   panes:
#     - name: terminal
#       command: ""
#     - name: server
#       command: "npm run dev"
#     - name: main
#       command: "claude"
#
# shared_volume:
#   enabled: true
#   path: ~/.crabterm/shared
#   link_as: .local
#
# submodules:
#   - path: my-submodule
#     reset_to: origin/main
EOF

  _init_set_default_if_first "$alias_input"

  echo ""
  success "Project @$alias_input registered at $CONFIG_FILE"
  echo ""
  echo -e "${CYAN}Next steps:${NC}"
  echo ""
  echo "  1. Run 'crab @$alias_input config scan' to detect .env files and ports"
  echo "  2. Edit $CONFIG_FILE to set your layout commands:"
  echo "     - server pane: your dev server command (e.g., pnpm dev)"
  echo "     - main pane: your main tool (e.g., claude)"
  echo "  3. Run 'crab @$alias_input ws 1' to create your first workspace"
  echo ""
}

# Helper: set as default project if it's the first one registered
_init_set_default_if_first() {
  local alias="$1"
  local count=0
  for f in "$PROJECTS_DIR"/*.yaml; do
    [ -f "$f" ] || continue
    count=$((count + 1))
  done

  if [ "$count" -le 1 ]; then
    mkdir -p "$CONFIG_DIR"
    if [ -f "$GLOBAL_CONFIG" ] && yq -r '.default_project' "$GLOBAL_CONFIG" &>/dev/null; then
      yq -i ".default_project = \"$alias\"" "$GLOBAL_CONFIG"
    else
      cat > "$GLOBAL_CONFIG" << EOF
# Crabterm Global Configuration
default_project: $alias
EOF
    fi
    echo -e "  ${GREEN}Set as default project${NC} (use 'crab default' to change)"
  fi
}

# =============================================================================
# Config Scan - Discover env files and provide template
# =============================================================================

config_scan() {
  echo -e "${CYAN}Scanning for .env files in main repo...${NC}"
  echo ""

  if ! config_exists; then
    error "No config file found. Run 'crab init' first."
    return 1
  fi

  load_config

  local repo_path=$(expand_path "$MAIN_REPO")
  if [ ! -d "$repo_path" ]; then
    error "Main repo not found: $repo_path"
    return 1
  fi

  local env_files=""
  local file_count=0

  # Only scan for .env files (not .env.example) since we copy from main repo
  while IFS= read -r file; do
    [ -z "$file" ] && continue
    env_files="$env_files$file"$'\n'
    file_count=$((file_count + 1))
  done < <(find "$repo_path" -maxdepth 3 -type f -name ".env" ! -path "*/node_modules/*" ! -path "*/.git/*" 2>/dev/null | sort)

  if [ $file_count -eq 0 ]; then
    echo "  No .env files found in $repo_path"
    echo ""
    echo "  You can manually configure env_sync in $CONFIG_FILE"
    return 0
  fi

  echo -e "Found ${GREEN}${file_count}${NC} .env file(s) in main repo:"
  echo ""

  echo "$env_files" | while IFS= read -r file; do
    [ -z "$file" ] && continue
    local rel_path="${file#$repo_path/}"
    echo -e "  ${BOLD}$rel_path${NC}"
  done

  echo ""
  echo -e "${CYAN}Add to $CONFIG_FILE:${NC}"
  echo ""
  echo "env_sync:"
  echo "  files:"

  echo "$env_files" | while IFS= read -r file; do
    [ -z "$file" ] && continue
    local rel_path="${file#$repo_path/}"
    echo "    - path: $rel_path        # copied from main repo"
    echo "      ports: []              # e.g., [API_PORT, ADMIN_PORT]"
    echo "      # refs:                # optional: URL vars that reference ports"
    echo "      #   VITE_API_URL: API_PORT"
    echo "      # overrides:           # optional: override specific vars per workspace"
    echo "      #   DEBUG: \"true\""
  done

  echo ""
  echo -e "${CYAN}How it works:${NC}"
  echo "  - Each file is copied from the same path in your main repo"
  echo "  - ports: vars crab manages (increments per workspace, checks availability)"
  echo "  - refs: URL vars that reference a managed port (auto-rewritten)"
  echo "  - overrides: set specific env vars differently in workspaces"
}

show_config() {
  if ! config_exists; then
    echo -e "${YELLOW}No config file found.${NC}"
    echo "Run 'crab init' to create one."
    return
  fi

  echo -e "${CYAN}Crabterm Configuration${NC}"
  if [ -n "${PROJECT_ALIAS:-}" ]; then
    echo "Project: @$PROJECT_ALIAS"
  fi
  echo "File: $CONFIG_FILE"
  echo ""
  cat "$CONFIG_FILE"
}
